### ISSUE TITLE
Lower JDK requrement to 1.6

### ISSUE THREAD

**Issue by yerenkow** [aggregateknowledge/java-hll#4]
Would be great to have java-hll working with Java 1.6 out-of-maven.

**Comment by blinsay** [comment]
We'll take a quick look this afternoon and see how easy that is. If it's just a `pom.xml` change, we'll try and push it sometime today or tomorrow. If code has to change, it might be closer to the end of the week.

**Comment by yerenkow** [comment]
**pom.xml** / maven-compiler-plugin

``` xml
                    <source>1.6</source>
                    <target>1.6</target>
```

works for me instantly :)

**Comment by ghost** [comment]
@yerenkow This should appear in Maven Central in a bit under v1.4.0. Sorry about the delay!
